apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pharma
  namespace: argocd
  labels:
    managed-by: terraform
spec:
  description: Pharma microservices project

  sourceRepos:
    - "https://github.com/roland-zen-devops/zen-gitops.git"

  destinations:
    - server: https://kubernetes.default.svc
      namespace: dev
    - server: https://kubernetes.default.svc
      namespace: argocd

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  orphanedResources:
    warn: false

  roles:
    - name: pharma-admin
      description: Admin role for pharma project
      policies:
        - p, proj:pharma:pharma-admin, applications, *, pharma/*, allow
      groups:
        - pharma-devops-team
